### PR TITLE
Night Mode added

### PR DESCRIPTION
**Pull request by amuroBosetti**
This adds a new slider on the left menu that allows to switch between the regular Gobstones aspect and a new dark mode. This is made by changing the ACE editor theme to "gruvbox", and also toggling the "night" class, that is modified by a new stylesheet, dark.css

### CODE REVIEW

**Comment by rodri042** [comment]
Awesome!! Could you rename "changeTheme" to "nightMode"?

I'll merge test and merge it soon. Thanks

**Comment by fidel-ml** [comment]
Remember to give proper credit in the "About to"... ;)
FF

**Comment by amuroBosetti** [comment]
> Remember to give proper credit in the "About to"... ;) FF
> […](#)

@fidel-ml not entirely sure about what you mean. Are you referring to adding something to "Colaboradores" in about-gobstones?

**Comment by fidel-ml** [comment]
Rodrigo debería agregar tu nombre como autor en la parte que corresponde...
;)
FF

**Pull request merged**
